reference_case_name: b1850.f19_g17.validation_mct.004

compare_case_name:
    - b1850.f19_g17.validation_mct.002
    - b1850.f19_g17.validation_nuopc.004

case_data_paths:
     - /glade/scratch/hannay/archive/b1850.f19_g17.validation_mct.004/ocn/hist
     - /glade/scratch/hannay/archive/b1850.f19_g17.validation_mct.002/ocn/hist
     - /glade/scratch/hannay/archive/b1850.f19_g17.validation_nuopc.004_copy2/ocn/hist

cesm_file_format:
     - hist
     
catalog_csv: ../data/cesm-validation-catalog.csv
    
catalog_json: ../data/cesm-validation-catalog.json

variables:
    physics:
        - TEMP
        - SALT
        - HMXL
        - BSF
        - IFRAC
        - SHF
        - SFWF
        - SHF_QSW
    biogeochemistry:
        - FG_CO2
        - PO4
        - photoC_TOT_zint
        - photoC_sp_zint
        - photoC_diat_zint
        - photoC_diaz_zint
        - POC_FLUX_100m
        - diaz_Nfix
        - SiO2_PROD
        - CaCO3_FLUX_100m
        - SiO2_FLUX_100m
        - ALK
        - DIC
        - O2
        - DOC
        - DOCr
        - NH4
        - NO3
        - SiO3
  