name: bgc-diagnostics-dev
channels:
    - conda-forge
    - nodefaults
    - pyviz
dependencies:
    - bokeh
    - bottleneck
    - distributed
    - dask
    - ncar-jobqueue
    - xarray
    - pyyaml
    - intake-esm
    - holoviews
    - hvplot
    - datashader
    - panel
    - matplotlib
    - jupyterlab
    - ecgtools
    - geoviews
    - nbterm
    - nbformat
